Explicitly cast to the smaller unsigned type to silence a gcc warning as error.
```
In file included from /home/runner/work/highway/highway/hwy/foreach_target.h:72,
                 from /home/runner/work/highway/highway/hwy/contrib/bit_pack/bit_pack_test.cc:27:
/home/runner/work/highway/highway/hwy/contrib/bit_pack/bit_pack_test.cc: In instantiation of ‘void hwy::N_SSSE3::TestPack<PackT, kVectors, kBits>::operator()(T, D) [with T = unsigned char; D = hwy::N_SSSE3::Simd<unsigned char, 16, 0>; PackT = hwy::N_SSSE3::Pack8; long unsigned int kVectors = 8; long unsigned int kBits = 1]’:
/home/runner/work/highway/highway/hwy/tests/test_util-inl.h:256:13:   required from ‘static void hwy::N_SSSE3::detail::ForeachCappedR<T, kMul, kMinArg, Test, kPow2>::Do(size_t, size_t) [with T = unsigned char; long unsigned int kMul = 8; long unsigned int kMinArg = 2; Test = hwy::N_SSSE3::TestPack<hwy::N_SSSE3::Pack8, 8, 1>; int kPow2 = 0; size_t = long unsigned int]’
/home/runner/work/highway/highway/hwy/tests/test_util-inl.h:439:74:   required from ‘void hwy::N_SSSE3::ForShrinkableVectors<Test, kPow2>::operator()(T) const [with T = unsigned char; Test = hwy::N_SSSE3::TestPack<hwy::N_SSSE3::Pack8, 8, 1>; int kPow2 = 1]’
/home/runner/work/highway/highway/hwy/contrib/bit_pack/bit_pack_test.cc:165:58:   required from here
/home/runner/work/highway/highway/hwy/contrib/bit_pack/bit_pack_test.cc:151:49: error: conversion from ‘int’ to ‘unsigned char’ may change value [-Werror=conversion]
       packed.get()[Random32(&rng) % num_packed] += Unpredictable1() - 1;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
```

#2011