Introduce a macro for reinterpret_cast special case
In some case we know it is acceptable to increase alignement. Hint the
compiler when doing so.

Solve typical warning messages:

highway/hwy/ops/ppc_vsx-inl.h:619:35: error: cast from 'const long unsigned int* __restrict__' to 'const LoadRaw*' {aka 'const __vector(2) long unsigned int*'} increases required alignment of target type [-Werror=cast-align]
  619 |   const LoadRaw* HWY_RESTRICT p = reinterpret_cast<const LoadRaw*>(aligned);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~